version: '3.8'

services:
  mongodb:
    image: mongo:6.0  # Use latest stable or specify your desired version
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
