version: '3.8'

services:
  backend:
    image: beauty-agenda-backend
    ports:
      - "5001:5001"
    environment:
      GOOGLE_CLIENT_ID: "<client-id>.apps.googleusercontent.com"
      JWT_SECRET: "token-secret"
      ALLOWED_EMAIL: "mail@gmail.com"

  mongodb:
    image: mongo:6.0  # Use latest stable or specify your desired version
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
