FROM ubuntu:20.04

RUN apt update

RUN apt install -y wget && rm -rf /var/lib/apt/lists/*

RUN apt update && apt install python3-pip -y

WORKDIR /api
COPY . /api

RUN pip3 install -r requirements.txt

CMD ["python3", "api.py"]

