version: '3'

services:
  mongodb:
    image: mongo:6.0 
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    image: gonperna/beautyagenda:backendv3
    container_name: backend
    ports:
      - "5001:5001"

  beautyagenda:
    image: gonperna/beautyagenda:v3
    container_name: beautyagenda
    ports: 
      - "3000:3000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - certbot
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done"
    restart: unless-stopped

volumes:
  mongo_data: